name: simplenotes

services:
  db:
    image: postgres:16
    restart: unless-stopped
    container_name: db
    volumes:
      - simplenotes-db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    networks:
      - simplenotes-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    container_name: backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/auth_site/.env
    depends_on:
      - db
    networks:
      - simplenotes-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - simplenotes-network

volumes:
  simplenotes-db_data:

networks:
  simplenotes-network:
    driver: bridge
